### ISSUE TITLE
webkit detection error

### ISSUE THREAD

**Issue by pixelpaulaus** [Pixofield/keyshapejs#11]
i noticed this code
`var isWebkit = navigator.vendor.match(/apple/i);`
causes errors in older browsers due to .vendor browser support.
I myself changed it to this...
`var isWebkit = /webkit/.test( navigator.userAgent );`
which i believe is more compatible with older browsers.

**Comment by Pixofield** [comment]
Which web browsers are giving errors for it? You must have been testing some very old web browsers.

I can change it to `/apple/i.test(navigator.vendor)` so that it doesn't fail if `navigator.vendor` isn't defined.

The purpose of the `isWebkit` flag is to check if the web browser is Safari (it should really be called `isSafari`). It should be `true` if running on Safari and `false` if running on other browsers.

You code sets `isWebkit` to `true` also for Chrome. It doesn't break anything, but it makes  animations a bit slower on Chrome.

**Comment by Pixofield** [comment]
This has been fixed in Keyshape 1.12.0 and KeyshapeJS 1.2 to `/apple/i.test(navigator.vendor)`.
